image: $CI_REGISTRY/signageos/docker-node:8.9.0-alpine-build

stages:
  - prepare
  - test
  - build
  - publish

cache:
  untracked: true
  key: "$CI_PROJECT_ID"
  paths:
    - node_modules/

before_script:
  - npm config set unsafe-perm true
  - TAG=$([ "$CI_COMMIT_TAG" == "" ] && echo $CI_COMMIT_REF_NAME || echo "latest")
  - VERSION=`cat ./VERSION`
  - tools/npm-login
  - npx @signageos/lib@just-tools version-upgrade $VERSION
  - mkdir -p dist
  - npm install --tag $TAG

prepare:
  stage: prepare
  before_script: []
  script:
    - VERSION=$([ "$CI_COMMIT_TAG" == "" ] && echo `git describe --abbrev=0 --tags`-$CI_COMMIT_REF_NAME.$CI_PIPELINE_IID || echo $CI_COMMIT_TAG)
    - VERSION=${VERSION:1}
    - echo -n $VERSION > ./VERSION
  artifacts:
    when: on_success
    paths:
      - ./VERSION

test:lint:
  stage: test
  except:
    - tags
  script:
    - npm run lint

build:
  stage: build
  dependencies:
    - prepare
  script:
    - npm run prepublish --production
  artifacts:
    when: on_success
    paths:
      - dist/

publish:npm:
  stage: publish
  dependencies:
    - prepare
    - build
  script:
    - npm publish --ignore-scripts --tag $TAG
